make compatible with mautic 5.x
roghumi/IrSmsBundle pull request #1
Opened 2022-09-01 20:50 UTC by mhd-jalilvand

make compatible with mautic 5.x
tested with 5.x and 4.1
fixes some errors on php 7.4.30

2022-09-03 17:36 UTC, peynman approved these changes
compatible with php 7

2022-09-03 17:38 UTC, peynman requested changes
thanks for your contrib. please remove helloworld stuff so i can merge

2022-09-03 19:33 UTC, mhd-jalilvand commented
Thank you too for your publishing your plugin. The helloworld files are removed.

2022-09-04 09:08 UTC, peynman approved these changes

2022-09-04 09:09 UTC, merged